language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nawabkibria/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nawabkibria/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-019015173296"
  bucket_path: "docker-react"
  on:
    branch: dev
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
